
from lsqpy import Matrix

a = Matrix([[1,2,3]])
b = Matrix([[6,5,4]])
c = Matrix([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])
d = Matrix([10,12,13])
print('a = ')
print(a)
print('b = ')
print(b)
print('c = ')
print(c)
print('d = ')
print(d)

# Run some tests
print('-------------------------------------')
print('ADD AND SUB')
print('-------------------------------------')
print('a+b')
print(a+b)
print('------------')
print('a-b')
print(a-b)
print('------------')
print('-a')
print(-a)
print('------------')
print('a+6')
print(a+6)
print('------------')
print('6+a')
print(6+a)
print('-------------------------------------')
print('TRANSPOSE')
print('-------------------------------------')
print(a.T)
print('-------------------------------------')
print('MUL AND DIV')
print('-------------------------------------')
print('a*b.T')
print(a*b.T)
print('------------')
print('a.T*b')
print(a.T*b)
print('------------')
print('6*a')
print(6*a)
print('------------')
print('a*6')
print(a*6)
print('------------')
print('a/2')
print(a/2)
print('-------------------------------------')
print('INDEXING')
print('-------------------------------------')
print('c = ')
print(c)
print('------------')
print('c[1,1]')
print(c[1,1])
print('------------')
print('c[1,1:4]')
print(c[1,1:4])
print('------------')
print('c[0:2,1:4]')
print(c[0:2,1:4])
print('------------')
print('c[[0,2],1:4]')
print(c[[0,2],1:4])
print('------------')
print('c[[0,2],[0,1,3]]')
print(c[[0,2],[0,1,3]])
print('-------------------------------------')
print('RESHAPE')
print('-------------------------------------')
print('c.reshape(1,12)')
print(c.reshape(1,12))